#!/usr/bin/env bash

# Update and upgrade packages without prompt
apt update && apt upgrade -y

# Install a few packages
pkg install -y openssh grep

# Start SSH server
sshd

# Set a password for user
PASSWD=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1`
echo -e "${PASSWD}\n${PASSWD}" | passwd

# doesn't seem to do what I want
#echo "PermitEmptyPasswords yes" >> ~/../usr/etc/ssh/sshd_config

# Get SSH server port
SSHD_PORT=`logcat -d -s 'syslog:*' | grep -m1 -Po "sshd - Server listening on .* port \K\d+"`

GREEN="\e[32m"
YELLOW="\e[33m"
END_COLOR="\e[m"
echo -e "${GREEN}From your computer, find this phone's IP by running ${YELLOW}arp -a${END_COLOR}"
echo -e "${GREEN}Then run ${YELLOW}ssh-copy-id -p $SSHD_PORT {IP}${END_COLOR}"
echo -e "${GREEN}Your password is ${YELLOW}${PASSWD}${END_COLOR}"
